### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Kingfoxl** [eithe/NRKTV.bundle#19]
Hi, i have set up my first plex and with it, your nrk app. Can't get it to work though. Get "please check that the file exists" etc. Installed it on my plex server and try to watch on my pht.

**Comment by burnbay** [comment]
Hi!

What version of PLEX server are you running? And PHT version? Do you see the channel at all in PHT?

**Comment by Kingfoxl** [comment]
Hi, sorry for not being clearer in the original post, was making dinner while handling my son and talking to my wife. :) I am using the newest stabile of everything. PHT: Version 1.3.5.431-7966a4df  - Server:  Version 0.9.11.7.803-87d0708 Ubuntu
I downloaded the channel from the plex channel downloader. Everything is visible in PHT. Server is on Ubuntu Server 14.04, PHT is on Windows 8.1.
Would it perhaps help downloading the zip from here, or is it the same version as in plex?

**Comment by eithe** [comment]
Should be the same as one of the Plex devs just pulled our latest version, but worth a try. Please report back!

**Comment by Kingfoxl** [comment]
Think i figured it out. My home server is running through VPN in the Netherlands, and that is probably blocked from NRK's side. Sorry for bothering you. :)
